[project]
name = "voicefilter"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "ffmpeg-normalize>=1.37.6",
    "ipykernel>=7.2.0",
    "librosa>=0.11.0",
    "matplotlib>=3.10.9",
    "mir-eval>=0.8.2",
    "numpy>=2.4.4",
    "pillow>=12.2.0",
    "pyyaml>=6.0.3",
    "speechbrain",
    "tensorboardx>=2.6.5",
    "torch>=2.11.0",
    "torchaudio>=2.11.0",
    "torchcodec>=0.11.1",
    "tqdm>=4.67.3",
    "wrapt>=2.1.2",
]

[tool.uv.sources]
speechbrain = { git = "https://github.com/speechbrain/speechbrain.git", tag = "develop" }
